ProjectPythia/cookbook-actions

.github/workflows/build-book.yaml

This is required for using ARM data

Add arm doe portal details

---

.github/workflows/build-book.yaml

Fix the credentials section of the cookbook actions

FIX: Move to env instead of with

---

.github/workflows/delete-preview.yaml

Another step toward https://github.com/ProjectPythiaCookbooks/cookbook-template/issues/61

New reusable delete-preview action

---

.github/workflows/deploy-book.yaml

This should fix #9 and get this working.

Remove needs

---

.github/workflows/link-checker.yaml

Check to see if the `_config.yml` file exists before trying to modify it.

Check for config file existence

---

.github/workflows/build-book.yaml

This undoes the changes in #37 and tries out a new action to test if the environment file has changed. 
Will need to merge for some experimental testing.

Revert binder test condition; test out new logic

---

.github/workflows/build-book.yaml

More testing of logic to handle changes in environment file

New logic to choose which ref to use for binder image

---

.github/workflows/build-book.yaml

Add some debugging output

---

.github/workflows/build-book.yaml

Fix syntax

---

.github/workflows/build-book.yaml

Use the correct syntax for the name of a step output

Fix reference to step output

---

.github/workflows/build-book.yaml

Closes #49 
This will enable us to pass repo secrets to binderhub execution

Add secrets to binderhub execution

---

.github/workflows/build-book.yaml

As of now, the cmip6-cookbook execution is failing due to comment blocks in the run section - this fixes the syntax

Fix the comment block syntax in the build cook action

---

.github/workflows/preview-comment.yaml

More syntax fixes to #56 and #57

use GITHUB_OUTPUT

---

.github/workflows/preview-comment.yaml

Case insenstive string comparison

---

.github/workflows/build-book.yaml
.github/workflows/get-code.yaml

Support for the option of building PR previews with secrets

---

.github/workflows/build-book.yaml

correct binderbot secrets syntax

---

.github/workflows/build-book.yaml

Hopefully this fixes #73 
Will have to merge and then test over in https://github.com/ProjectPythia/cookbook-template/pull/128

Fix repo name and ref for binder call with updated environment

---

.github/workflows/build-book.yaml

Use new action for env variables

---

.github/workflows/build-book.yaml

Fix what I just did

---

.github/workflows/build-book.yaml

Add in new fields required for AQS and NASA Earthdata environment variables

ADD: Add new fields for AQ cookbook data portals

---

.github/workflows/build-book.yaml

See the [portal issue #457](https://github.com/ProjectPythia/projectpythia.github.io/issues/457) for details. This PR attempts to only temporarily fix the publish-site until we figure the actual issue with v45

Downgrade tj-actions/changed-files from v45 to v44 for temporary fix

---

.github/workflows/link-checker.yaml

Another attempt to resolve #126.
Maybe we need to enclose the version pin in quotes. Will have to merge this first before testing.

try to fix conda syntax

---

.github/workflows/deploy-book.yaml

remove debug steps

---

.github/workflows/deploy-book.yaml

I just noticed that we had the wrong path specified in `clean-exclude`. 
This PR might fix #133

Fix path to previews
