.github/workflows/build-book.yaml
Secrets do not allow passing the type and default values.
See https://github.com/ProjectPythiaCookbooks/radar-cookbook/actions/runs/3053946245
This removes those parameters from the secrets
=> FIX: Remove invalid parameters default and type for arm credentials

.github/workflows/deploy-book.yaml
This makes the `deploy-book.yaml` reusable workflow more general. We should be able to use it at least twice for every PR: once to deploy the preview, and once to deploy the final result.
It will be the responsibility of the calling workflow to provide the right path for the preview as input argument `destination_dir`.
=> Add destination-dir option

.github/workflows/deploy-book.yaml
This is needed to use this infrastructure to publish Pythia Foundations, which needs a custom CNAME when deployed to GitHub Pages.
Should be fully backwards compatible, but can't actually test without merging (an example of why #6 is needed).
=> Add optional cname argument for deploy

.github/workflows/build-book.yaml
Attempt to generalize the `build_book.yaml` so that it can handle sphinx sites as well as jupyterbook.
=> add build_command option

.github/workflows/build-book.yaml
Seems that the variable substitution `${{ inputs.path_to_notebooks }}` doesn't work when we're still in the inputs section. This is a workaround.
=> Fix what I just broke

.github/workflows/link-checker.yaml
This adds an optional `build_command` input argument for the `link-checker.yaml` workflow, similar to the `build-book.yaml` workflow.
The use case is passing `make linkcheck` to run the sphinx link-checker for repos that are build with Sphinx rather than JupyterBook.
=> New build_command argument for link-checker.yaml

.github/workflows/build-book.yaml
This fixes a potential bug in the existing book building code. This is preventing the cmip6-cookbook from rebuilding the image
=> Ensure env is rebuilt when use cached env is set to false

.github/workflows/preview-comment.yaml
Thank you so much for these super useful actions. 
This PR adds an optional input argument for the preview comment action to enable more customized reuse of the action (outside of the ProjPythia specific context).  This should be backwards compatible as far as I can tell.
=> Add optional argument to customize preview comment

.github/workflows/deploy-book.yaml
I have been implementing these actions over at the [LEAP Technical Docs](https://github.com/leap-stc/leap-stc.github.io), but I am running into issues since our book directory (and the resulting build directory) is nested one level down from the root. 
I believe if I can specify the `publish_dir` with a custom value (see [our old deploy script](https://github.com/leap-stc/leap-stc.github.io/blob/9819491a2a508e54ec7633cf2d57a3a2c29cd99c/.github/workflows/deploy.yaml#L45)) this would enable me to fully reuse this set of actions.
I will test this out over there and report back.
=> Enable custom `publish_dir` in deploy-book action

.github/workflows/preview-comment.yaml
Addresses #47 and https://github.com/ProjectPythia/projectpythia.github.io/issues/329
The preview workflow checks to see if the repo name matches the pattern `{repo owner}.github.io`, in which case this is a ["User/Org" site](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites) rather than a Project site.
User/Org sites post the preview to `https://{repo owner}.github.io/_preview/{PR number}`, whereas Project sites post the preview to `https://{repo owner}.github.io/{repo name}/_preview/{PR number}`.
=> Adapt preview URL for org or project site

.github/workflows/build-book.yaml
Over at https://github.com/leap-stc/ClimSim/tree/main I am using the `jb-article` format and also specify a custom builder to concatenate several source files into one html page. 
This somehow puts the built html into a different subfolder. `_build/singlehtml` vs the hardcoded `_build/html`. 
This PR enables the user to specify the output directory. 
> I suspect that the output files are always put into a `_build/<builder specified>` scheme? So maybe the input should rather be the builder only? Or are there cases where the `_build` part of the path is named differently?
=> Make path to output an input argument

.github/workflows/build-book.yaml
Adds new input argument for the `build-book.yaml` workflow
```
binder_nb_timeout
```
which gets passed on to binderbot as `--nb-timeout`. The default value is 600 seconds which matches the existing binderbot default.
Should be backwards-compatible, and won't affect builds that don't use binderbot.
This will enable building heavier-duty Cookbooks (https://github.com/ProjectPythia/cesm-lens-aws-cookbook/pull/16)
=> Add option to change binder timeout

.github/workflows/build-book.yaml
Currently, we are not passing the secrets to the build command on Github actions. This makes sure that is added in.
=> Add missing secrets in non-binder build

.github/workflows/build-book.yaml
Pin `sphinxcontrib-applehelp` to 1.0.7 to fix [cookbook-template - Issue #154](https://github.com/ProjectPythia/cookbook-template/issues/154) for now (until the theme issues can be fixed permanently).
=> Update build-book.yaml to temporarily fix nightly build failures with Sphinx version issue

.github/workflows/build-book.yaml
PR #91 had touched only `sphinxcontrib-applehelp` for temporarily pinning it to get Cookbook builds up and running again. However, it turned out it was not sufficient, several other `sphinxcontrib-...` packages have also been updated over a few days ago (e.g. now `sphinxcontrib-devhelp` started to fail the cookbook builds). This PR pins them all to their previous versions with which our Cookbooks had built successfully. 
Additionally, issue #93 has been created to take care of these temporary pinnings in the future once we have an updated Sphinx theme.
=> Update build-book.yaml to temporarily pin sphinxcontrib-... packages

.github/workflows/build-book.yaml, .gitignore
I am unsure on why this step to trigger the build-build lives inside of the book-build. Let me know what you think.
E: Thanks @brian-rose for explaining that it doesn't trigger the trigger-book-build.yaml workflow, but tells the book-build action to look in that action for the artifact.
Related to https://github.com/ProjectPythia/projectpythia.github.io/pull/415 and https://github.com/ProjectPythia/projectpythia.github.io/issues/319
=> Make `workflow-trigger` an input to download artifact step

.github/workflows/build-book.yaml
Getting error:
```
[Invalid workflow file: .github/workflows/nightly-build.yaml#L11](https://github.com/jukent/projectpythia.github.io/actions/runs/8398301725/workflow)
The workflow is not valid. In .github/workflows/nightly-build.yaml (Line: 11, Col: 11): Error from called workflow ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main (Line: 52, Col: 9): Required property is missing: type
```
This specifies that it is a string.
=> missing type for trigger_workflow

.github/workflows/build-book.yaml
From my branch action's error:
```
Run dawidd6/action-download-artifact@v3.1.4
==> Repository: jukent/projectpythia.github.io
==> Artifact name: repo-zip
==> Local path: ./
==> Workflow name: input.trigger_workflow
==> Workflow conclusion: success
==> Allow forks: true
Error: Not Found - https://docs.github.com/rest/actions/workflow-runs#list-workflow-runs-for-a-workflow
```
I made one of 2 mistakes (or both). The action looks for a workflow called input.trigger_workflow, instead of looking for what was inputed. It should be inputs (plural) and potentially have curly brackets around it to indicate that it is a variable. 
Related to https://github.com/ProjectPythia/projectpythia.github.io/issues/319 and https://github.com/ProjectPythia/projectpythia.github.io/pull/415
=> Update build-book.yaml to fix input workflow

.github/workflows/build-book.yaml
Was limiting artifact search to workflows produced by completed workflows "Workflow conclusion: success" and thus not finding the automated metrics produced within the workflow.
We don't want to specify workflow_conclusion and run_ID together though -- still working out why workflow_conclusion was defaulting to success when unspecified and with a run_ID
=> workflow_conclusion was defaulting to success when we want the option

.github/workflows/build-book.yaml
We shouldn't need to pin sphinx packages anymore with the release of sphinx-pythia-theme v2024.3.0.
This PR removes the temporary pins, and should close #93
=> Remove temporary sphinx-contrib... pins

.github/workflows/build-book.yaml, .github/workflows/deploy-book.yaml
Since PR #108 got rid of the pins for older versions of several packages we had had to use with the older pythia theme, no much change was needed here since "Update execution env" step uses the env file of whatever repo calls book build.
=> Start using the updated theme

.github/workflows/build-book.yaml
We are missing the api-cookbook secrets in the actual build part of the action - this adds it in
=> FIX: Fix missing secrets in build step

.github/workflows/build-book.yaml, .github/workflows/link-checker.yaml
Closes #123 
This PR replaces Mambaforge with Miniforge (and `mamba` commands with `conda`) throughout our workflows. Function should be identical. The change is necessary due to the [sunsetting of Mambaforge](https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/).
=> Switch from mambaforge to miniforge

.github/workflows/link-checker.yaml
This should resolve #126 and get the link checker running again.
We can leave #126 open until things are fixed upstream and the version pin can be removed.
=> pin to Python < 3.13

.github/workflows/deploy-book.yaml
Closes https://github.com/ProjectPythia/cookbook-actions/issues/120
Switch to use jamesives/github-pages-deploy-action@v4
=> Swap PR preview action

.github/workflows/deploy-book.yaml
This is an attempt to fix our deployment over at https://github.com/leap-stc/leap-stc.github.io which broke after #125 (I foolishly used @main)
I think that the input names needed to be adjusted, but crucially I had to checkout the repo in the deploy workflow to get this to run. 
I have confirmed that our [main deployment](https://github.com/leap-stc/leap-stc.github.io/actions/runs/11404520305) and a [test PR](https://github.com/leap-stc/leap-stc.github.io/pull/190).
Overall I think this emphasizes the need for #6. Some sort of an end-to-end test would have presumably caught this?
=> Potential follow up fix for #125

.github/workflows/deploy-book.yaml
Previews are being deleted when the main site is deployed. This PR might fix this.
=> Fix syntax for clean-exclude

.github/workflows/deploy-book.yaml
As discussed in #129, the new deployment action doesn't support a `CNAME` argument for deployment to custom domains. But we don't need this. It's a one-time step to put a `CNAME` file at the root of the `gh-pages` branch, and we are only using this for two repositories (Foundations and Cookbook Gallery).
This PR removes the `cname` input option for the `deploy-book.yaml` workflow.
We'll need to tweak the workflow code that calls this from the Foundations and Cookbook Gallery repos.
=> Remove custom domain name option

.github/workflows/build-book.yaml, .github/workflows/deploy-book.yaml
This PR updates the `build-book.yaml` workflow in two important ways:
- uses micromamba to set up the execution environment (much faster) and gets rid of the environment caching (no longer needed with micromamba performance)
- Add a new input argument `base_url` which is necessary for building with MyST
The calling workflow needs to specify `build_command: 'myst build --execute --html'` (and include mystmd in its environment file) for this to work with MyST.
Everything here *should* be backwards compatible but we will have to do some manual checking that existing non-MyST builds still work (#6 still unresolved).
=> Add MyST compatibility
